[package]
name = "external"
version = "0.5.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# env
dotenv = { workspace = true }
# Https server framework
actix = { workspace = true }
actix-web = { workspace = true }
# To serialize and deserialize objects from json
serde = { workspace = true }
serde_json = { workspace = true }
# For logging and debugging
log = { workspace = true }
# date and time
chrono = { workspace = true }
# ORM
reqwest = { workspace = true }
anyhow = { workspace = true }
service_utils = { path = "../service_utils" }
experimentation_platform = { path = "../experimentation_platform" }
superposition_types = { git = "ssh://git@ssh.bitbucket.juspay.net/picaf/context-aware-config.git", version = "0.1.0" }
dashboard-auth = { git = "ssh://git@ssh.bitbucket.juspay.net/picaf/sdk-rs-utils.git", tag = "v1.9.0" }
