version: "3.4"
services:
  application:
    container_name: "application"
    command: ./context-aware-config
    build:
      dockerfile: Dockerfile
      context: .
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      # to access postgres outside of docker, use postgres://postgres:docker@localhost:5432 instead
      - DATABASE_URL=postgres://postgres:docker@postgres:5432/config?sslmode=disable
      - DB_POOL_SIZE=10

    networks:
      - library-network
    tty: true
    ports:
      - "8080:8080"

  postgres:
    build: ./docker-compose/postgres/
    container_name: context-aware-config_postgres
    environment:
      POSTGRES_PASSWORD: "docker"
      POSTGRES_DB: "config"
    networks:
      - library-network
    ports:
      - "5432:5432"

  localstack:
    build : ./docker-compose/localstack/
    container_name: context-aware-config_localstack_instance
    ports:
      - "4510-4559:4510-4559"  # external service port range
      - "4566:4566"            # LocalStack Edge Proxy
      - "4571:4571"
    network_mode: bridge
    environment:
      LOCALSTACK_SERVICES: s3, sns, sqs, logs, cloudwatch, kms
      AWS_DEFAULT_REGION: ap-south-1
      EDGE_PORT: 4566
    volumes:
      - ./docker-compose/localstack/export_cyphers.sh:/etc/localstack/export_cyphers.sh

networks:
  library-network:
    driver: bridge

