[dimensions]

# priority grows exponentially in powers of 2 starting with the first entry, highest priority items win
os = { pattern = "(android|ios|web)", type = "string", priority = 1 }     # priority 1
toss = { type = "number", priority = 2 }                                  # priority 2
clientId = { pattern = "^[a-z0-9].*$", type = "string", priority = 4 }    # priority 4
scope = { pattern = "(beta|release|cug)", type = "string", priority = 8 } # priority 8
internalUser = { type = "boolean", priority = 16 }                        # priority 16
tier = { type = "number", priority = 32 }                                 # priority 32

[default-configs]

android_hyperpay_version = "2.1.1_android"
android_godel_config = "1.0"
android_hyperpay_configuration = "hyperpay configuration android url"
android_hyperpay_strings = "hyperpay strings android url"
android_hyperpay_icons = "hyperpay icons android url"
android_hyperupi_version = "2.2.2_upi_android"
android_hyperupi_configuration = "hyperupi configuration android url"
android_hyperupi_strings = "hyperupi strings android url"
android_hyperupi_icons = "hyperupi icons android url"

ios_hyperpay_version = "2.1.1_ios"
ios_hyperpay_configuration = "hyperpay configuration ios url"
ios_hyperpay_strings = "hyperpay strings ios url"
ios_hyperpay_icons = "hyperpay icons ios url"
ios_hyperupi_version = "2.2.2_upi_ios"
ios_hyperupi_configuration = "hyperupi configuration ios url"
ios_hyperupi_strings = "hyperupi strings ios url"
ios_hyperupi_icons = "hyperupi icons ios url"

web_hyperpay_version = "2.1.1_web"
web_hyperpay_configuration = "hyperpay configuration web url"
web_hyperpay_strings = "hyperpay strings web url"
web_hyperpay_icons = "hyperpay icons web url"
web_hyperupi_version = "2.2.2_upi_web"
web_hyperupi_configuration = "hyperupi configuration web url"
web_hyperupi_strings = "hyperupi strings web url"
web_hyperupi_icons = "hyperupi icons web url"


["os = android"]
android_godel_config = "1.3"

["os = android and clientId IN [meesho,zee5]"]
android_hyperupi_version = "1_android"
android_hyperupi_configuration = "PICAF-22147"
android_hyperpay_version = "1.2.1_android"
android_hyperpay_configuration = "PICAF-22145"

["os = ios and clientId IN [a23games,galactustest]"]
ios_hyperupi_version = "10.2.2_upi_ios"

["os IN [web,ios] and toss = -1"]
ios_hyperupi_icons = "PICAF-22146"

["clientId = cac"]
android_hyperpay_version = "1.2.1_android"
android_hyperpay_configuration = "PICAF-22145"

["tier IN [1,2]"]
android_hyperpay_version = "1.0.1_android"
# godel_config = "1.0"
