[package]
name = "cac_client"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
chrono = "0.4.26"
jsonlogic = "0.5.1"
reqwest = { version = "0.11.18", features = ["json"]}
once_cell = { version = "1.18.0" }
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.97"
log = "^0.4"
json-patch = "1.0.0"
derive_more = "^0.99"